#### FIG ENV VARIABLES ####
# Please make sure this block is at the start of this file.
[ -s ~/.fig/shell/pre.sh ] && source ~/.fig/shell/pre.sh
#### END FIG ENV VARIABLES ####

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Custom folder
ZSH_CUSTOM=$HOME/aluminium/dotfiles/zsh

# Theme
ZSH_THEME=""

# Plugins
plugins=(git zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# Include z, yo
. ~/aluminium/dotfiles/zsh/z.sh

# Pure https://github.com/sindresorhus/pure
autoload -U promptinit; promptinit
prompt pure

# Defaults
export EDITOR=code

# Aliases
source ~/aluminium/dotfiles/zsh/aliases.zsh

# History
source ~/aluminium/dotfiles/zsh/history.zsh

# Private settings
source $HOME/Dropbox/dotfiles/private.zsh

# nvm
export NVM_DIR="$HOME/.nvm"

if [ -s "$NVM_DIR/nvm.sh" ]; then
  . "$NVM_DIR/nvm.sh"
fi

# bin
export PATH="$HOME/bin:$PATH"

# yarn
export PATH="$HOME/.yarn/bin:$PATH"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

#### FIG ENV VARIABLES ####
# Please make sure this block is at the end of this file.
[ -s ~/.fig/fig.sh ] && source ~/.fig/fig.sh
#### END FIG ENV VARIABLES ####
