# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Custom folder
ZSH_CUSTOM=$HOME/dotfiles/zsh

# Theme
ZSH_THEME=""

# Plugins
plugins=(git zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# Include z, yo
. ~/dotfiles/z.sh

# Pure https://github.com/sindresorhus/pure
autoload -U promptinit; promptinit
prompt pure

# Defaults
export EDITOR=code

# Aliases
source ~/dotfiles/zsh/aliases.zsh

# History
source ~/dotfiles/zsh/history.zsh

# Private settings
[ -f ~/dotfiles/zsh/private.zsh ] && source ~/dotfiles/zsh/private.zsh

# nvm
export NVM_DIR="$HOME/.nvm"

if [ -s "$NVM_DIR/nvm.sh" ]; then
  . "$NVM_DIR/nvm.sh"
fi

# bin
export PATH="$HOME/bin:$PATH"

# yarn
export PATH="$HOME/.yarn/bin:$PATH"
